AEIP-18 token resupply implementation
archethic-foundation/archethic-node pull request #1209
Opened 2023-08-01 14:55 UTC by bchamagne

# Description

Implement AEIP-18: token resupply
Fixes #1174 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual scenario:
- create a fungible token
- create a resupply transaction
- utxos should have the same token_address

![Screenshot_2023-08-01_16-04-41](https://github.com/archethic-foundation/archethic-node/assets/74045243/a67b5299-1188-4a67-bd66-446e41ab0c94)

plus a few unit tests

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-08-04 09:05 UTC, Neylix requested changes
I could be nice to also add test in ledger operation for token resuply

2023-08-07 06:56 UTC, bchamagne commented on lib/archethic/mining/pending_transaction_validation.ex
> +        case {ExJsonSchema.Validator.validate(@token_schema, json_token),
I've done this while working on the issue #1175.

2023-08-07 06:56 UTC, bchamagne commented on lib/archethic/mining/pending_transaction_validation.ex
> +    with {:ok, token_address} <- Base.decode16(token_ref, case: :mixed),
I've done it in #1175 as well

2023-08-07 06:57 UTC, bchamagne commented on lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
> +        type: {:token, Base.decode16!(token_ref), 0},
Done in #1175

2023-08-07 06:57 UTC, bchamagne commented on priv/json-schemas/token-resupply.json
> +            "type": "string",
Done in #1175

2023-08-07 09:24 UTC, bchamagne commented on lib/archethic/mining/pending_transaction_validation.ex
> +         {:ok, genesis_address} <- fetch_previous_tx_genesis_address(tx),
I committed in #1175 https://github.com/archethic-foundation/archethic-node/compare/2566253d027672e6f561c9cdc43eeaff216003c5..e844e0f257893176a130585b7a93aa469b28a74b

2023-08-22 12:42 UTC, merged