restrict smart contract functions
archethic-foundation/archethic-node pull request #1212
Opened 2023-08-03 13:38 UTC by aime-risson

# Description
 - [X] do not allow function call from pub function
 - [ ] private function can only call public function
 - [ ] restrict module access to functions
## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-08-07 15:25 UTC, bchamagne commented on lib/archethic/contracts/interpreter/common_interpreter.ex
> +    case Enum.find(functions, fn
maybe the `defp function_exists?(functions, function_name, arity) do` from conditionInterpreter shall be extracted and re-used?

2023-08-07 15:28 UTC, bchamagne commented on lib/archethic/contracts/interpreter/function_interpreter.ex
> +  alias Knigge
not needed :dancers:

2023-08-07 15:47 UTC, bchamagne approved these changes
LGTM

2023-08-08 12:55 UTC, Neylix requested changes

2023-08-08 12:55 UTC, Neylix commented on lib/archethic/contracts/interpreter/function_interpreter.ex
> +      Code.ensure_loaded!(
Maybe this control could be created as a function in `library` module as `module_exists?`. So you could use it in all interpreter.

2023-08-08 12:55 UTC, Neylix commented on lib/archethic/contracts/interpreter/function_interpreter.ex
> +           {{:., _meta, [{:__aliases__, _, [atom: "Contract"]}, {:atom, function_name}]}, _, _},
I you create a `Library.module_exists?` function, you could create a single prewalk that control both io and write contract tags

2023-08-08 12:55 UTC, Neylix commented on lib/archethic/contracts/interpreter/function_interpreter.ex
> +        String.to_existing_atom("Elixir.Archethic.Contracts.Interpreter.Library.Contract")
Since this module will soon support function that do not write the contract, it could goes in Common module

2023-08-08 12:55 UTC, Neylix commented on test/tag_test.exs
> +      assert !ModuleExample.tagged_with?(:print, :not_there)
You could use `refute` over using `!` statement

2023-08-10 08:35 UTC, Neylix approved these changes

2023-08-10 09:49 UTC, merged