Dashboard does not use metrics anymore
archethic-foundation/archethic-node pull request #1333
Opened 2023-11-28 13:59 UTC by bchamagne

# Description

With 21 nodes, we used to transmit more than 100GB per node per day to display the dashboard. 

Before: `21 nodes * 300KB of data * 720 requests per hour * 24 hours = 100GB`
After: `21 nodes * 4KB of data * 60 requests per hour * 24 hours = 121MB`

I removed the fetching of metrics from nodes to nodes and replaced it with 2 new processes: 
- DashboardAggregator listens to local events and keep them in buckets
- DashboardAggregatorAggregator request regularly other nodes for their DashboardAggregator data 

The aggregation is currently set to 1 minute and we keep 60 minutes of history. This way the dashboard can display the last hour of data as soon as we hit the page.

We could do smaller buckets / longer history if the need arises.

Fixes #1182

<img width="1568" alt="Capture d’écran 2023-11-28 à 14 18 22" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/3ee588c3-ce41-4356-b939-44d2fda19bc7">

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Unit tests + tested locally with 4 nodes

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-12-14 12:41 UTC, Neylix requested changes
For the naming you could rename `DashboardAggregator` to `DashboardMetrics` and `DashboardAggregatorAggregator` to `DashboardMetricsAggregator` it looks nicer I think

2023-12-14 12:41 UTC, Neylix commented on test/archethic_web/dashboard_aggregator_test.exs
> +    # the DashboardAggregator is already started and supervised
This could be avoided by using the `enabled` attribute in test config. So the setup could be just to start the GenServer using `start_supervised`

2023-12-14 12:41 UTC, Neylix commented on test/archethic_web/dashboard_aggregator_aggregator_test.exs
> +    # the DashboardAggregatorAggregator is already started and supervised
Same as DashboardAggregator for test config

2023-12-14 12:47 UTC, Neylix commented
I also have weird behavior running 2 nodes:

![image](https://github.com/archethic-foundation/archethic-node/assets/26260538/9f55dbcc-41e9-446f-aa4c-8580e9f4cbcf)

Also there is something wrong in the calculation of number of transaction. Currently for a bucket of a timestamp you create a list of all the durations of all nodes, but some durations of different node refer the same transaction, so if you have only one transaction processed by 3 nodes you'll say there where 3 transactions processed in the graph while in fact there were only 1 transaction.

A solution could be to have a map with transaction address => duration, so you could easily calculate the real number of transaction, and it would also be a more accurate calculation of the average transaction validation time

2023-12-20 16:51 UTC, Neylix approved these changes

2023-12-20 16:51 UTC, Neylix commented on lib/archethic_web/explorer/live/dashboard_live.ex
> +    |> Enum.sort(fn {{_, datetime_a}, _}, {{_, datetime_b}, _} ->
**Suggestion**
You can use `Enum.sort_by` here
```elixir
Enum.sort_by(fn {{_, datetime}, _} -> datetime end, {:asc, DateTime})
```

2023-12-20 18:38 UTC, bchamagne commented
<img width="1580" alt="Capture d’écran 2023-12-20 à 19 36 38" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/b35d7a34-b8c9-4679-b12e-f1ca96ebb82b">

2023-12-21 11:30 UTC, Neylix commented on lib/archethic_web/explorer/live/dashboard_live.ex
> +        {timestamp, div(sum, count) / 1_000_000}
Why do you divide by 1_000_000, this result in 0.00035 ms on the graph which is invalid

2023-12-21 19:27 UTC, bchamagne commented
<img width="1563" alt="Capture d’écran 2023-12-21 à 20 21 37" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/2fc77550-50d0-483c-9d59-0c0b6d54b523">

2023-12-22 11:56 UTC, Neylix approved these changes

2023-12-22 13:22 UTC, merged