GetUnspentOutputs optimization
archethic-foundation/archethic-node pull request #1348
Opened 2023-12-11 18:58 UTC by bchamagne

# Description

Fixes #1316 

## Type of change

Refactor

# How Has This Been Tested?

Unit tested

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-12-12 16:44 UTC, samuelmanzanera approved these changes

2023-12-15 10:00 UTC, Neylix requested changes

2023-12-15 10:00 UTC, Neylix commented on lib/archethic/p2p/message/get_unspent_outputs.ex
> +      unspent_outputs: Enum.reverse(utxos),
This `Enum.reverse` were not here before and you didn't change the order of the list, so I guess you should not reverse the list here

2023-12-20 15:50 UTC, Neylix approved these changes

2023-12-20 15:50 UTC, merged