Fix GetUnspentOutputs deserialization
archethic-foundation/archethic-node pull request #1428
Opened 2024-02-14 09:38 UTC by bchamagne

2024-02-14 10:29 UTC, Neylix requested changes

2024-02-14 10:29 UTC, Neylix commented on lib/archethic/p2p/message/get_unspent_outputs.ex
> +  defstruct [:address, offset: 0, genesis?: false]
You should keep limit as it will surely be used in future graphql API as this request will become the new unspent output view after AEIP-21

2024-02-15 14:16 UTC, samuelmanzanera approved these changes
LGTM

2024-02-15 14:31 UTC, Neylix approved these changes

2024-02-15 14:31 UTC, merged