Set a minimum concurrency so it is never 0
archethic-foundation/archethic-node pull request #1430
Opened 2024-02-14 10:21 UTC by bchamagne

Avoid this error: 

```
** (ArgumentError) :max_concurrency must be an integer greater than zero
    (elixir 1.14.1) lib/task/supervised.ex:181: Task.Supervised.stream/7
    (elixir 1.14.1) lib/stream.ex:1811: Enumerable.Stream.do_each/4
    (elixir 1.14.1) lib/stream.ex:942: Stream.do_transform/5
    (elixir 1.14.1) lib/enum.ex:4307: anonymous fn/3 in Enum.concat_enum/1
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-concat_enum/1-lists^foldl/2-1-"/3
    (elixir 1.14.1) lib/enum.ex:2468: Enum.concat_enum/1
    (archethic 1.4.7) lib/archethic/self_repair/notifier.ex:185: Archethic.SelfRepair.Notifier.get_previous_election/3
```

2024-02-14 10:27 UTC, Neylix requested changes

2024-02-14 10:27 UTC, Neylix commented on lib/archethic/mining.ex
> +        max_concurrency: max(System.schedulers_online(), nb_storage_nodes),
nb_storage_nodes cannot be 0 so it is better to set the max_concurrency to nb_storage_nodes than scheduler online

2024-02-14 10:27 UTC, Neylix commented on lib/archethic/mining/distributed_workflow.ex
> +        max_concurrency: max(System.schedulers_online(), length(storage_nodes))
Same here

2024-02-14 10:27 UTC, Neylix commented on lib/archethic/transaction_chain/transaction_summary.ex
> +      max_concurrency: max(System.schedulers_online(), length(addresses))
There is a pattern matching in function definition ensuring addresses is not empty

2024-02-14 10:27 UTC, Neylix commented on lib/archethic/utxo.ex
> +        max_concurrency: max(System.schedulers_online(), length(movements) + length(recipients))
There is a guard ensuring there is a least one movement or recipient

2024-02-15 14:15 UTC, Neylix approved these changes

2024-02-15 14:17 UTC, samuelmanzanera approved these changes
LGTM

2024-02-15 14:28 UTC, merged