Add geopatch to node transactions
archethic-foundation/archethic-node pull request #1605
Opened 2024-11-24 18:24 UTC by wassimans

# Description

This pull request introduces the **systematic** addition of a geopatch to node transactions. This change ensures that the geopatch is included in node transactions and validated during the transaction lifecycle.

The update impacts the election of storage and validation nodes, as it now relies on the validated geopatch from node transactions rather than local calculations. This approach resolves inconsistencies caused by potential updates to the MMDB2 database.

This change introduces:
	•	The inclusion of the geopatch in node transactions.
	•	Migration script to add the geopatch to existing nodes transactions.
	•	Updated tests to validate the geopatch functionality.
	•	Enhanced core modules for encoding, decoding, and validating geopatches.

Fixes #1576 #1613

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Functional Tests

- Functionally validated the migration script by running it on a network of test nodes.
- Verified the inclusion of the geopatch in updated transactions and ensured proper validation in subsequent operations.
- Transaction Content Validation: Validated that node transactions include geopatch information and that it is correctly decoded during transaction processing.
- Invalid Geopatch Handling: Ensured that transactions with invalid geopatches are rejected.

## Unit Tests

- Enhanced existing test cases for Node.encode_transaction_content/1 and Node.decode_transaction_content/1 to include geopatch validation.
- Added new tests in GeoPatchTest for geopatch calculation and decoding.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2024-11-27 16:20 UTC, Neylix requested changes

2024-11-27 16:20 UTC, Neylix commented on priv/migration_tasks/prod/1.5.14@add_geopatch_node_transactiosn.ex
> +      TransactionChain.get_last_transaction(genesis_address, data: [:code])
`P2P.get_node_info` returns the last_address of the node in the Node struct. You could directly use this last_address using the function `TransactionChain.get_transaction()`

2024-11-27 16:20 UTC, Neylix commented on priv/migration_tasks/prod/1.5.14@add_geopatch_node_transactiosn.ex
> +        PubSub.register_to_new_transaction_by_type(:node)
Before registering to pubsub you could check if the last transaction of the node does not already contains a geopatch

2024-11-27 16:20 UTC, Neylix commented on priv/migration_tasks/prod/1.5.14@add_geopatch_node_transactiosn.ex
> +  defp process_transaction(transaction) do
I don't get the purpose of this function since in any case do the same instruction and return `{:cont, :ok}`

2024-11-27 16:20 UTC, Neylix commented on priv/migration_tasks/prod/1.5.14@add_geopatch_node_transactiosn.ex
> +              if first_pk == node_pk do
I think if you receive a transaction from an other node than expected you should have a specific behavior. For example if you are waiting for Node1 transaction and you receive Node2 transaction, you will continue in the list and then wait for Node2 transaction, but you just received it

2024-11-28 08:56 UTC, wassimans commented on test/archethic/p2p/geo_patch_test.exs
> +  test "includes and validates geopatch in a node transaction" do
Moved the two tests to pending transaction validation tests. We have now two tests for invalid geopatches: one that asserts on the returned error message from PendingTransactionValidation.validate_type_rules/2, and one that asserts on the expected geopatch.

2025-02-07 18:02 UTC, Neylix approved these changes

2025-02-11 12:21 UTC, merged