Add transaction fee api, fix archethic-foundation/archethic-node#196
archethic-foundation/archethic-node pull request #200
Opened 2022-01-21 11:51 UTC by roychowdhuryrohit-dev

Added transaction fee api for calculating and sending fee of transaction body received
Added new route for transaction fee api
Added testcases for transaction body validation

2022-01-21 12:01 UTC, samuel-uniris requested changes
Thanks for the PR.
Just one comment regarding the inclusion of the UCO price provider.

2022-01-21 12:10 UTC, roychowdhuryrohit-dev commented on lib/archethic_web/controllers/api/transaction_controller.ex
> +          "uco_price_provider" => @ucoprice_provider
For transparency towards end user, we should provide the information that the calculation has been powered by Coingecko data. But then again it's a personal opinion.

2022-01-21 12:40 UTC, samuel-uniris commented on lib/archethic_web/controllers/api/transaction_controller.ex
> +          "uco_price_provider" => @ucoprice_provider
We can provide information about the rates of the UCO price, so client applications can display the real price of the transaction's fee. We assume the UCO price is given and aggregated by the network, so with consensus.

Exemple of payload
```js
{
  fee: 0.4942,
  uco_rates: {
    usd: 0.2,
    eur: 0.22
   }
 }
 ```

2022-01-21 13:34 UTC, samuel-uniris approved these changes

2022-01-21 13:36 UTC, merged

2022-01-23 16:51 UTC, redDwarf03 commented
hello
could you explain me why these fields are mandatory when I send a request to /api/transaction_fee ?
                  "originSignature"
                  "previousPublicKey" 
                  "previousSignature"

I would like to get the estimation of a transaction before sending to inform user how much could they pay to send tx.
so when I want to display estimation of fee, I have just the address of the owner, the balance, the amount and the recipient

thx