Resolve dark mode in echarts #244 || add dark mode
archethic-foundation/archethic-node pull request #310
Opened 2022-05-10 07:56 UTC by apoorv-2204

# Description

- [ ] Remove issue with forced dark mode

- [ ] add simple dark mode archethic.net 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2022-05-11 07:26 UTC, apoorv-2204 commented
> Enforce white background in dark mode .

![vmware_eppj712VNp](https://user-images.githubusercontent.com/90304197/167792626-6060ee48-8ee8-4cbf-a6e5-9f8ad04157bf.png)

![vmware_J2lwm0xWMS](https://user-images.githubusercontent.com/90304197/167792640-dfd5d4c1-57f4-4ab6-87ff-2dde670d0d08.png)

2022-05-11 10:58 UTC, Neylix requested changes

2022-05-11 10:58 UTC, Neylix commented on assets/js/app.js
> +    var explorer_metric_obj = metric_config_obj.create_explorer_live_visuals(1);
The parameter "1" is not expected in `create_explorer_live_visuals` function

2022-05-11 12:43 UTC, Neylix approved these changes

2022-05-12 06:45 UTC, samuel-uniris approved these changes

2022-05-12 06:47 UTC, merged