notify welcome node
archethic-foundation/archethic-node pull request #475
Opened 2022-07-26 03:20 UTC by imnik11

# Description
notifying transaction subscriber with error along with the reason of failure.

Fixes #445 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

yet to be best way tested

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2022-08-01 08:30 UTC, apoorv-2204 commented
Proposed new changes is: nEW message struct %P2P.TransactionStatus{
address: txn_address,
status: (1234) : validated, pending, failed. timeout, etc. 
}

2022-08-01 08:40 UTC, imnik11 commented
ok

2022-08-04 13:23 UTC, samuel-uniris requested changes

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/p2p/message/error.ex
> +          | :workflow_error
I don't think workflow error is really useful, we should keep as network issue

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +    Task.start(fn ->
You should use the Task.Supervisor to avoid process without supervision

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +    {:next_state, {:return_error, "mining_timeout"}, data}
I think this should be network issue error

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +        {:next_state, {:return_error, "No_coordinator_error"}, data}
I think this should be network issue error

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +    {:next_state, {:return_error, "replication_error"}, data}
You should take the reason of the error as input to notify back to the welcome node

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +    {:next_state, {:return_error, "consensus_error"}, data}
I think this should be network issue error

2022-08-04 13:23 UTC, samuel-uniris commented on lib/archethic/mining/distributed_workflow.ex
> +        {:next_state, {:return_error, "No_cross_validation_error"}, data}
I think this should be network issue error

2022-08-05 13:10 UTC, samuel-uniris approved these changes

2022-08-05 13:12 UTC, merged