Verify scheduled transaction only happens once
archethic-foundation/archethic-node pull request #534
Opened 2022-08-19 16:12 UTC by samuel-uniris

# Description

Ensure network transactions which are scheduled to happen only once in their interval.

Fixes #421 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Start a node at the beginning of a minute, the network init should initialize the transactions and create the first node shared tx.
At the 40th s, the scheduler try to send another tx.
The validation should catch it and the tx would not be validated.
But for the next minute this should be validated, as the last scheduling date would have change.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2022-08-22 13:03 UTC, apoorv-2204 requested changes
maybe test cases under mining_pending_validation_test.exs

2022-08-22 16:01 UTC, samuel-uniris commented on lib/archethic/shared_secrets.ex
> +      |> DateTime.truncate(:millisecond)
Not we need filter millisecond to make datetime more predictble and also we are not using interval in ms.

2022-08-23 07:57 UTC, apoorv-2204 approved these changes
:+1:

2022-08-23 09:49 UTC, samuel-uniris commented on lib/archethic/shared_secrets.ex
> +      |> DateTime.truncate(:millisecond)
Sorry my bad, you're right

2022-08-23 14:47 UTC, samuel-uniris commented on lib/archethic/mining/pending_transaction_validation.ex
> +      {:ok, %Transaction{validation_stamp: %ValidationStamp{timestamp: timestamp}}} ->
We check if in the interval we don't get another tx after the scheduling time.
So only a transaction can be sent in this interval.

2022-08-25 14:57 UTC, merged