Fix dashboard
archethic-foundation/archethic-node pull request #554
Opened 2022-09-01 16:47 UTC by samuelmanzanera

# Description

Fix the dashboard metrics aggregation and plotting.

Fixes #455 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

By running transactions the graphs should be updated with up/down lines.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2022-09-05 06:02 UTC, apoorv-2204 commented
LGTM: ![Screenshot_20220905_113042](https://user-images.githubusercontent.com/90304197/188370842-9899498d-b2be-4e9c-8710-6fae62d43ea8.png)

2022-09-05 06:23 UTC, apoorv-2204 requested changes
Looks nice to me.

2022-09-05 06:23 UTC, apoorv-2204 commented on assets/js/metric_config.js
> -  update_guage_data(metric_obj.archethic_p2p_send_message_duration, points, "archethic_p2p_send_message_duration");
Unused guage methods can be removed.

2022-09-05 06:23 UTC, apoorv-2204 commented on assets/js/metric_config.js
>      shifted_value = 0;
We can remove ,line 135..242. of guage object

2022-09-05 06:23 UTC, apoorv-2204 commented on lib/archethic/telemetry.ex
> +        reporter_options: [
can we split to more buckets?

2022-09-05 06:34 UTC, samuelmanzanera commented on lib/archethic/telemetry.ex
> +        reporter_options: [
Yes we can if we need

2022-09-09 15:43 UTC, apoorv-2204 commented on assets/js/metric_config.js
>  function exponent_formatter(new_point) {
this can also be removed

2022-09-26 21:34 UTC, closed without merging