Valid the authorized nodes in the node shared secret
archethic-foundation/archethic-node pull request #715
Opened 2022-11-24 19:32 UTC by tenmoves

# Description

Actually during the pending validation, we control if the new authorized nodes in the node shared secret transaction are part of the candidate, but we do not verify if the selected ones are the good ones.
We should not verify if the new authorized nodes are part of the candidate, but directly verify that all authorized nodes are the same as the return of the function NodeRenewal.next_authorized_node_public_keys()

# Possible enhancement
If we don't need the order we should probably use a different a data structure, it seems a MapSet is more adapted in this case.

Fixes #694 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

we make sure that the authorized nodes in the transaction are exactly the same as the ones returned by 
next_authorized_node_public_keys function
# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2022-11-28 09:00 UTC, samuelmanzanera commented on lib/archethic/mining/pending_transaction_validation.ex
> +           authorized_keys
I think it will be more clear without the pipeline by extracting variables and do simple comparison.

2022-11-29 21:50 UTC, Neylix requested changes

2022-11-29 21:50 UTC, Neylix commented on lib/archethic/mining/pending_transaction_validation.ex
> +         true <- sorted_authorized_keys == sorted_node_renewal_authorized_keys do
You may add a unit test to ensure the error when both list are different.
Otherwise it works well :+1:

2022-11-30 11:28 UTC, Neylix approved these changes

2022-11-30 12:44 UTC, samuelmanzanera approved these changes

2022-11-30 12:44 UTC, merged