Explorer optimizations (read DB before asking network when possible)
archethic-foundation/archethic-node pull request #784
Opened 2022-12-16 13:38 UTC by bchamagne

# Description

Fetch explorer's data from DB if it is available on current node. This avoid plenty of network requests.
**ALSO**: Refactored a bit the pagination to be consistent across all pages

Fixes #730

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested the explorer 

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-01-02 09:16 UTC, bchamagne commented
As discussed with @Neylix , the same optimisation can be used on many functions from the `Archethic` module.
Plus, I should not run an election to determine if the node has the local data, because elections change over time (they are based on the currently available nodes).

2023-01-02 14:23 UTC, bchamagne commented
and of course I messed up with the rebase

2023-01-02 19:22 UTC, Neylix requested changes

2023-01-02 19:22 UTC, Neylix commented on lib/archethic.ex
> +  def transaction_exists?(address) do
This function can check the DB before asking network, using `TransactionChain.transaction_exists?` if it return false, then we ask the network. This function can check both in db storage or io storage

2023-01-03 11:56 UTC, Neylix approved these changes

2023-01-03 11:58 UTC, merged