attempt to resolve  upnp_port_forwarding_fail_on_local_ip_change#698
archethic-foundation/archethic-node pull request #793
Opened 2022-12-29 07:26 UTC by apoorv-2204

# Description

attempt to resolve  upnp_port_forwarding_fail_on_local_ip_change#698

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-01-05 15:11 UTC, bchamagne approved these changes
Just read the code, I did not test it.

2023-01-05 15:11 UTC, bchamagne commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +    with {reason, status} when status != 0 <- System.cmd(@upnpc, map_query(local_ip, port)),
I find this pattern very hard to read

2023-01-05 15:16 UTC, samuelmanzanera requested changes

2023-01-05 15:16 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +    with {reason, status} when status != 0 <- System.cmd(@upnpc, map_query(local_ip, port)),
I think using the happy path firstly, we would make more sense.
The error branching should be done on the else, I think.

2023-01-05 15:16 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +    with {reason, status} when status != 0 <- System.cmd(@upnpc, map_query(local_ip, port)),
We could use something like this:
```elixir
case System.cmd(@upnpc, map_query(local_ip, port)) do
  {_, 0} ->
    :ok 
  {reason, status} ->
    reason
    |> parse_reason()
    |> handle_error()
 end
```

2023-01-05 15:16 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +      {:error, :conflict_in_mapping_entry}
The error tuple is more used to help to branch between success and failure.
Here you just want to format error's reason.
I think you could return simplify the error's reason, so you could easily use this function in a pipeline.

2023-01-05 15:16 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +      {_, 0} -> :ok
I think you could leverage the reopening in the error's handling.

2023-01-05 18:42 UTC, apoorv-2204 commented
![image](https://user-images.githubusercontent.com/90304197/210856242-cd6f8e08-ae56-4864-bd74-6ce72fd1cef9.png)

2023-01-05 23:32 UTC, samuelmanzanera requested changes

2023-01-05 23:32 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +  def do_open_port(local_ip, port, retires \\ 2)
You might keep it private

2023-01-05 23:32 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +      "-e",
Last time we got some issue with this parameter. Need to check with @Neylix

2023-01-06 15:11 UTC, bchamagne commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +  defp do_open_port(local_ip, port, retires) do
typo: `retries`

ps: very good idea

2023-01-06 15:48 UTC, samuelmanzanera commented on lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
> +      {reason, status} when status != 0 ->
I think you can omit the status check

2023-01-06 18:47 UTC, samuelmanzanera reviewed
Code seems ok

2023-01-10 14:50 UTC, Neylix approved these changes

2023-01-10 14:50 UTC, merged