Forwarding random port with upnpc #700
archethic-foundation/archethic-node pull request #810
Opened 2023-01-05 15:33 UTC by apoorv-2204

# Description

We chose a random port , from a list of unassigned  ports as per IANA.

Fixes 

- [ ] #700 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Manual
![image](https://user-images.githubusercontent.com/90304197/210818559-562c9839-9cb0-4540-a3e7-66539211b4dd.png)

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-01-05 23:29 UTC, samuelmanzanera requested changes

2023-01-05 23:29 UTC, samuelmanzanera commented on lib/archethic/networking/port_forwarding.ex
> +  @iana_registry_path Path.join([
You should put non mutable (by code) resources in the priv folder .

2023-01-05 23:29 UTC, samuelmanzanera commented on lib/archethic/networking/port_forwarding.ex
> +  defp list_iana_unassigned_ports() do
I think you could simplify without the need to list the port from IANA. Between 49152 through 65535 should make it. 
The randomness could be recursive until one port is free.

2023-01-06 14:17 UTC, samuelmanzanera reviewed
Code seems ok for me

2023-01-06 14:17 UTC, samuelmanzanera approved these changes

2023-01-06 15:29 UTC, bchamagne commented
I see some functions that use this code are completely ignoring the random port:

ex:  Archethic.Networking.Scheduler

```
  defp open_ports do
    p2p_port = Application.get_env(:archethic, P2PListener) |> Keyword.fetch!(:port)
    web_port = Application.get_env(:archethic, WebEndpoint) |> get_in([:http, :port])

    with {:ok, _} <- PortForwarding.try_open_port(p2p_port, false),
         {:ok, _} <- PortForwarding.try_open_port(web_port, false) do
      {:ok, p2p_port, web_port}
    end
  end
```

2023-01-06 15:30 UTC, bchamagne commented
what about HTTP(S) port, you don't want to open random port for them (ex: ArchethicWeb.Supervisor.init)

2023-01-06 15:33 UTC, bchamagne commented
> what about HTTP(S) port, you don't want to open random port for them (ex: ArchethicWeb.Supervisor.init)

Not an issue, I didn't notice the `force = false` flag.

2023-01-06 18:06 UTC, samuelmanzanera approved these changes

2023-01-11 12:10 UTC, samuelmanzanera commented
@apoorv-2204 Could you check why the CI is not passing ?

2023-01-11 14:16 UTC, apoorv-2204 commented
> @apoorv-2204 Could you check why the CI is not passing ?

Thanks for pointing it out

2023-01-11 16:46 UTC, Neylix reviewed
On line 21 of PortForwarding module, if the function `do_try_open_port` return an error, the fallback is never called so the random port is never published

2023-01-11 17:27 UTC, apoorv-2204 commented
> On line 21 of PortForwarding module, if the function `do_try_open_port` return an error, the fallback is never called so the random port is never published

```  {:ok, port} <- do_try_open_port(port) do
      {:ok, port}```

2023-01-12 14:19 UTC, Neylix approved these changes

2023-01-12 14:19 UTC, merged