Draft: add get_calls/1 SC action
archethic-foundation/archethic-node pull request #822
Opened 2023-01-12 08:54 UTC by bchamagne

# Description

This PR aims at adding a `get_calls/1` function to the smart contracts' actions. 
This function can be used to create aggregator contracts that do not do anything until some threshold.
I found few issues along the way that I will create and fix outside of this PR. 

- [ ] Create a get_calls/0 that will automatically add the contract.address 
- [ ] Update smart contract documentation

Should the get_calls/1 be available outside the action block?

Fixes #512

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have tested with this contract: 

```
condition inherit: [
	type: true,
	content: true,
	uco_transfers: true
]

condition transaction: [
	uco_transfers: size() > 0
]

actions triggered_by: transaction do
	transactions = get_calls(contract.address)
	set_content size(transactions)
	set_type transfer
	add_uco_transfer to: "000030831178cd6a49fe446778455a7a980729a293bfa16b0a1d2743935db210da76", amount: 1337
end
```

When I trigger this contract, a new transaction in the contract chain have the content updated to "0". 
**Which is not what is expected**, we expect it to be "1". But this is due to another issue (LINK) that will be dealt with in another PR.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-01-12 10:22 UTC, samuelmanzanera commented on lib/archethic/contracts/interpreter/library.ex
> +    |> Enum.map(fn {address, _, _} -> address end)
I think you can reduce the iterations, using a single Enum.map

2023-01-12 10:22 UTC, samuelmanzanera commented on lib/archethic/contracts/interpreter/library.ex
> +    TransactionLookup.list_contract_transactions(contract_address)
Also you can optimize the reading by piping the contract_address

2023-01-12 10:25 UTC, samuelmanzanera commented
> Should the get_calls/1 be available outside the action block?

I think for now, we can keep it in the actions block

2023-01-13 16:59 UTC, bchamagne commented
As discussed with @Neylix , we should remove the get_calls/1 for 2 reasons: 

- 1: no use case yet
- 2: actual implementation look at calls in local node, which is fine for contract's address, but not for other contract's address. We would have to download the transactions from network. Downloading hundreds of them might not be efficient.

What do you think @samuelmanzanera ?

2023-01-25 15:00 UTC, Neylix requested changes

2023-01-25 15:00 UTC, Neylix commented on lib/archethic/db/embedded_impl/chain_reader.ex
> +          Transaction.t() | nil
As the function `read_transaction` this function should return a tuple `{:ok, tx}` or `{:error, reason}`

2023-01-25 17:30 UTC, Neylix approved these changes

2023-01-26 11:34 UTC, Neylix approved these changes

2023-01-26 11:34 UTC, merged