worker_should_not_be_executed_while_replicating_a_transaction_from_se…
archethic-foundation/archethic-node pull request #864
Opened 2023-01-25 15:32 UTC by apoorv-2204

…lf_repair_#852

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-01-26 11:50 UTC, Neylix requested changes

2023-01-26 11:50 UTC, Neylix commented on lib/archethic/replication.ex
> +  def ingest_transaction(tx = %Transaction{}, io_transaction?, self_repair? \\ false) do
I think there is no need to have a default value, the parameter is always present when we call this function. Just need to add a false parameter in bootstrap_test

2023-01-26 11:50 UTC, Neylix commented on lib/archethic/replication.ex
> +    # also called from bootstrap
I don't get this commentary, this function is not called from bootstrap. Only in replication and bootstrap_test

2023-01-26 13:40 UTC, Neylix approved these changes

2023-01-26 16:24 UTC, samuelmanzanera requested changes

2023-01-26 16:24 UTC, samuelmanzanera commented on lib/archethic/contracts/loader.ex
> +  def do_load_transaction(
I think it should be private.

2023-01-26 18:56 UTC, samuelmanzanera approved these changes

2023-01-30 08:52 UTC, Neylix approved these changes

2023-01-30 08:53 UTC, merged