SmartContracts: Pass the calls to Interpreter.execute/3 & create corresponding message
archethic-foundation/archethic-node pull request #967
Opened 2023-03-30 14:40 UTC by bchamagne

# Description

Create a `GetContractCalls` message. Then refactor the `Interpreter.execute/3` to have the calls as a parameter instead of doing some I/O from within the contract execution. 

The `Contract.get_calls()` is actually not really necessary anymore and we could tell the users there is a `calls` global variable available. 

I entirely removed the `get_calls` function from Legacy interpreter since it did not work at all anyway.
I also only added it for the `action` blocks since there are no use case to handle it in `condition` block.

Fixes #919

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Unit tests :heavy_check_mark: 
Manual tests: :grey_question: 

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

2023-04-19 15:09 UTC, bchamagne commented on lib/archethic/contracts/interpreter.ex
> +      "calls" => Enum.map(calls, &Constants.from_transaction/1),
No need, it's done by the worker already. 

You can test it with this contract: 

```
@version 1
condition transaction: []
condition inherit: [
  content: true
]

actions triggered_by: transaction do 
  calls = Contract.get_calls()
  count = List.size(calls)
  Contract.set_content(count)
end
```

I will add this contract in a playbook

2023-04-20 11:20 UTC, samuelmanzanera requested changes

2023-04-20 11:20 UTC, samuelmanzanera commented on lib/archethic/contracts/worker.ex
> +             Enum.uniq([oracle_tx | calls]),
I don't think this is a valid statement.
Oracle transaction does not target explicitly smart contract, hence it should not be part of the calls . It's for the reason there is a distinction between trigger and call transactions.

2023-04-20 15:45 UTC, Neylix approved these changes

2023-04-20 18:20 UTC, samuelmanzanera approved these changes

2023-04-20 18:21 UTC, merged